# Based on the "trust" template v0.1.1
# # https://github.com/japaric/trust/tree/v0.1.1

dist: trusty
language: rust
services: docker

rust: stable

env:
  global:
    - CRATE_NAME=cobalt
    # default job
    - TARGET=x86_64-unknown-linux-gnu

matrix:
  include:
    # Linux
    # - env: TARGET=x86_64-unknown-linux-gnu  # this is the default job
    - env: TARGET=x86_64-unknown-linux-musl

    # OSX
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # Testing other channels
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: beta
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

before_deploy:
  - sh ci/before_deploy.sh

cache: cargo
before_cache:
    # Travis can't cache files that are not readable by "others"
    - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

# TODO: Upload coverage
#after_success:
 #- travis-cargo --only stable coveralls --no-sudo --exclude-pattern="src/main.rs,src/new.rs,target/debug/build/"

#deploy:
  #api_key:
    #secure: IzxVmMO+mVWc4BSoB7Ek7L6Ye5FNrCI4fb/pIFitrQRmP3Cpuw7qMm5sxL5niiGaMRJHwce07ukyKsCNgs+64k8VwToUDPWy4F7+EbIHrjDOJtIY8TME+hUeaCmkMysuqUj1oKtDS+l8F+Yc42ZXNMqz/1kF/h6sGTRSmlzR3mc=
  #file_glob: true
  #file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  #on:
    #condition: $TRAVIS_RUST_VERSION = stable
    #tags: true
  #provider: releases
  #skip_cleanup: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7e08f15b115326957c31
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
