sudo: false
language: rust

env:
  global:
    - CRATE_NAME=cobalt
    - COVERALLS=0.0.6
    - WHEN=0.1.0

matrix:
  include:
    # Linux
    - env: TARGET=x86_64-unknown-linux-gnu

    # OSX
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # Testing other channels
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: beta
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

    - rust: nightly-2017-10-09
      env: CLIPPY_VERS="0.0.165"
      install:
        - if [[ `cargo +nightly-2017-10-09 clippy -- --version` != $CLIPPY_VERS* ]] ; then travis_wait cargo +nightly-2017-10-09 install clippy --vers "$CLIPPY_VERS" --force; fi
        - export PATH=$HOME/.cargo/bin:$PATH
      script:
        - cargo +nightly-2017-10-09 clippy --features "syntax-highlight,sass" -- -D warnings
    - rust: stable
      env: RUSTFMT=0.8.6
      install:
        - if [[ `rustfmt --version` != $RUSTFMT* ]] ; then travis_wait cargo install rustfmt --force --vers $RUSTFMT; fi
        - export PATH=$HOME/.cargo/bin:$PATH
      script:
        - cargo fmt -- --write-mode=diff

install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $TRAVIS_RUST_VERSION
  - source ~/.cargo/env || true
  - if [[ `cargo-when --version` != *$WHEN ]] ; then travis_wait cargo install cargo-when --force --vers $WHEN; fi
#  - travis_wait cargo install cargo-travis --force --vers $COVERALLS

script:
  - rustc -Vv
  - cargo -V
  - cargo check --verbose
  - cargo check --verbose --features "syntax-highlight,sass"
  - cargo test  --verbose
  - cargo test  --verbose --features "syntax-highlight,sass"

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: "R4P4oXBODF9LZW/ht2putfF4tg74aOjWVRZWu7ia4ORdpEQ++RkgO32SQLZsLeXsJbb/qbTa06FfD6MC8MWdmek4DvwlSAiHrykVyio3BCv4RHmeBtaIhmp0L7n608tDeoJZFXE08JkDtR6rS8OiQw1jt6GuNAVGYk7/Rhgpujo="
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  skip_cleanup: true

after_success:
  - cmake --version
  - cargo when --channel stable -e TARGET=x86_64-unknown-linux-gnu coverage

addons:
  apt:
    packages:
      # necessary for `cargo coveralls`
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake

cache:
  apt: true
  directories:
    - $HOME/.cargo
    - target/debug/deps
    - target/debug/build
before_cache:
    # Travis can't cache files that are not readable by "others"
    - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7e08f15b115326957c31
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
