sudo: false
language: rust

env:
  global:
    - CRATE_NAME=cobalt
    - RUSTFMT=0.8.3

matrix:
  include:
    # Linux
    - env: TARGET=x86_64-unknown-linux-gnu

    # OSX
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # Testing other channels
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: beta
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $TRAVIS_RUST_VERSION
  - source ~/.cargo/env || true
  - if ! which cargo-coveralls ; then cargo install cargo-travis ; fi
  - if ! which cargo-when ; then cargo install cargo-when ; fi
  - if [[ `rustfmt --version` != $RUSTFMT* ]] ; then travis_wait cargo when --channel stable install rustfmt --force --vers $RUSTFMT; fi
  - travis_wait cargo when --channel nightly install clippy --force || true

script:
  - rustc -Vv
  - cargo -V
  - cargo check --verbose
  - cargo check --verbose --features "syntax-highlight,sass"
  - cargo test  --verbose
  - cargo test  --verbose --features "syntax-highlight,sass"
  - if which cargo-clippy ; then cargo when --channel nightly clippy -- --version ; fi
  - if which cargo-clippy ; then cargo when --channel nightly clippy --features "syntax-highlight,sass" ; fi
  - cargo when --channel stable fmt -- --version
  - cargo when --channel stable fmt -- --write-mode=diff

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: "R4P4oXBODF9LZW/ht2putfF4tg74aOjWVRZWu7ia4ORdpEQ++RkgO32SQLZsLeXsJbb/qbTa06FfD6MC8MWdmek4DvwlSAiHrykVyio3BCv4RHmeBtaIhmp0L7n608tDeoJZFXE08JkDtR6rS8OiQw1jt6GuNAVGYk7/Rhgpujo="
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  skip_cleanup: true

after_success:
  - cmake --version
  - cargo when --channel stable -e TARGET=x86_64-unknown-linux-gnu coverage

addons:
  apt:
    packages:
      # necessary for `cargo coveralls`
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake

cache:
  apt: true
  directories:
    - $HOME/.cargo
    - target/debug/deps
    - target/debug/build
before_cache:
    # Travis can't cache files that are not readable by "others"
    - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7e08f15b115326957c31
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
