sudo: false
language: rust

env:
  global:
  - CRATE_NAME=cobalt

matrix:
  include:
  # Linux
  - env: TARGET=x86_64-unknown-linux-gnu

  # OSX
  - env: TARGET=x86_64-apple-darwin
    os: osx

  # Testing other channels
  - env: TARGET=x86_64-unknown-linux-gnu
    rust: beta
  - env: TARGET=x86_64-unknown-linux-gnu
    rust: nightly

  - env: COVERALLS=0.0.9
    install:
    - travis_wait cargo install cargo-travis --force --vers $COVERALLS
    script:
    - cmake --version
    - cargo coverage || true
  - env: RUSTFMT
    rust: 1.24.0  # `stable`: Locking down for consistent behavior
    install:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt -- --write-mode=diff
  - env: RUSTFLAGS="-D warnings"
    rust: 1.24.0  # `stable`: Locking down for consistent behavior
    install:
    script:
    - cargo check --features "sass" --tests
  - env: CLIPPY_VERSION="0.0.179"
    rust: nightly-2018-01-12
    install:
    - travis_wait cargo install clippy --version $CLIPPY_VERSION || echo "clippy already installed"
    script:
    - cargo clippy --features "sass" -- -D clippy

install:
- rustc -Vv
- cargo -V
- curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $TRAVIS_RUST_VERSION
- source ~/.cargo/env || true

script:
- cargo test --verbose
- cargo test --verbose --no-default-features
- cargo test --verbose --features "sass"

before_deploy:
- sh ci/before_deploy.sh

branches:
  only:
  # Release tags
  - /^v\d+\.\d+\.\d+.*$/
  - master

deploy:
  provider: releases
  api_key:
    secure: "R4P4oXBODF9LZW/ht2putfF4tg74aOjWVRZWu7ia4ORdpEQ++RkgO32SQLZsLeXsJbb/qbTa06FfD6MC8MWdmek4DvwlSAiHrykVyio3BCv4RHmeBtaIhmp0L7n608tDeoJZFXE08JkDtR6rS8OiQw1jt6GuNAVGYk7/Rhgpujo="
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  skip_cleanup: true

addons:
  apt:
    packages:
    # necessary for `cargo coveralls`
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
    - cmake

cache:
  apt: true
  cargo: true
before_cache:
# Travis can't cache files that are not readable by "others"
- chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7e08f15b115326957c31
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
